### ISSUE TITLE
ETS 6.1

### ISSUE THREAD

**Issue by marvin-w** [XKNX/xknxproject#232]
Support Schema Version 22 for ETS 6.1

**Comment by farmio** [comment]
We may already support it 😁 but we should add some tests. 
https://github.com/XKNX/xknxproject/pull/213

**Comment by farmio** [comment]
Seems like it works fine 😃

**Comment by farmio** [comment]
https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/diy-do-it-yourself/1333830-wer-nutzt-denn-eigentlich-alles-home-assistant?p=1873741#post1873741
