### ISSUE TITLE
project is too big

### ISSUE THREAD

**Issue by platini76** [XKNX/xknxproject#258]
project is 5,2 mb... i don't know why..  but after compresss in ets and check errors it remains 5.2 mb..
when I try to upload it says project too big.

**Comment by farmio** [comment]
Hi 👋! 
Have a look at https://github.com/XKNX/knx-frontend/issues/70

**Comment by platini76** [comment]
> Hi 👋! Have a look at [XKNX/knx-frontend#70](https://github.com/XKNX/knx-frontend/issues/70)

thanks! but I am very noob.. how to add it to nginx addon config?


domain: xxxxxx.duckdns.org
hsts: max-age=31536000; includeSubDomains
certfile: fullchain.pem
keyfile: privkey.pem
cloudflare: false
customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf

**Comment by marvin-w** [comment]
I opened an upstream issue here: https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/461

Please follow this thread.

As a workaround you may add this custom directive:

```nginx
client_max_body_size 100M;
```

**Comment by platini76** [comment]
> I opened an upstream issue here: [hassio-addons/addon-nginx-proxy-manager#461](https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/461)
> 
> Please follow this issue.
> 
> As a workaround you may add this custom directive:
> 
> ```nginx
> client_max_body_size 100M;
> ```

I am so stupid sorry... but where add this? to a file?  or in HA config? please give me a path..

**Comment by farmio** [comment]
It would go somewhere in HAs Server block. 
> servers: nginx_proxy/*.conf

Or, if you use the Addon, I guess somewhere in the Proxy Manager UI. 

Is this reverse proxy a default part of HA OS?
