### ISSUE TITLE
Paeste knxprod

### ISSUE THREAD

**Issue by ski7777** [XKNX/xknxproject#292]
Do you have plans to parse knxprod files to allow configuration of specific components?

**Comment by ski7777** [comment]
Why is this not planned? As far as I understand I need the knxprod files in order to program the components and know the features to assign group addresses.

**Comment by farmio** [comment]
This is a duplicate of #291 🤷

**Comment by farmio** [comment]
The used device application definitions are included in the knxproj files. I don't know what additional information we would get from knxprod files. 

(I closed this because I thought it was a duplicate of #291 - just now saw that this is about different files).

**Comment by farmio** [comment]
> As far as I understand I need the knxprod files in order to program the components

The intention of this project wasn't about programming KNX devices. 

We just want to get information out of a project file (group address names and DPT, etc.) to be able to use it in other systems (eg. Home Assistant) to interact with already provisioned KNX devices.
