### ISSUE TITLE
Modify and Export Project Files

### ISSUE THREAD

**Issue by FlRedder** [XKNX/xknxproject#304]
Hi 👋 

First I want to thank you for developing this library. It really works like a charm for extracting all relevant infos from a `.knxproj`-file 🙏 

In our project, we use your library in combination with `FastAPI` to make group address infos from multiple KNX installations available for, e.g., provisioning these in the open source IoT middleware `FIWARE`.

As we deal with several KNX installations in our project, which regularly require an update of the bus program/configuration, it would be really useful to **modify and export** an existing `.knxproj`-file. Especially, because our installation follows a standardized group address definition schema (depending on the implemented functions and used physical devices) leading to cumbersome and error-prone manual updates of the KNX project.

Do you have any plans on implementing an **export mechanism** for modified `KNXProject` objects or similar? I assume this would require some safeguarding, e.g., allowing only changes in fields that are independent from the manuafacturer etc. However, even changing the `name` or `address` of a `GroupAddress` object (while keeping the inter-object relationships) would already be a substantial advantage (such a bulk-modification operation is not even supported by the `ETS` afaik).

I'm eager to hear your optinion on that topic and apologize if a similar question was already raised here (I briefly looked for related issues but could find any).

**Comment by farmio** [comment]
Hi 👋! 
Do I understand it correctly, that you want a function to generate an ETS importable `.knxproj` file from a dict parsed by xknxproject? 
If so, this is not possible. We don't have any methods to write back to the xml structures, throw away most of the information contained in a knx project file and most importantly - I don't think we can generate valid signature files for the project so it wouldn't be ETS importable.

That said, I think there are ways to batch edit in ETS - you can batch move GAs, batch rename with the search and replace function, and maybe there are ETS Apps that can help even further.

**Comment by FlRedder** [comment]
Thank you very much for getting back to me that quickly.

You are correct, I was hoping that there is a way to export a modified project into a valid `.xknxproj` file that works with the `ETS` and could be used to update the bus program directly. Based on your code, I expected that it is not straightforward to manipulate and write back `ETS`-compatible files.

Regarding the signatures, do you refer to [this (p.4, for ETS 5.7)](https://support.knx.org/hc/en-us/article_attachments/360024169360):

> 1.2 Extended Import Restrictions
    ETS will import projects only from a trusted source, which means:
    1. The project originates (exported) from ETS itself
    2. The project originates from a KNX member (and only products of this member are contained in the project)
    This is done via a dedicated project signature, in case of 2 the KNX manufacturer shall obtain a unique signature. This implies that an ‘unreliable’ project import - from a source not trusted by ETS - is not possible!

Based on this, I agree with you that - without beeing certified by the KNX Association - it is not possible to modify and export an existing file, even if you find a way to keep any `ETS`-specific file contents.

Thanks, I will take a look at the features you mentioned and see if there are any other ETS Apps that fit our needs.
