### ISSUE TITLE
Parse communication objects?

### ISSUE THREAD

**Issue by samuelchassot** [XKNX/xknxproject#32]
Hi,

I am working on an open source research project about smart home and verification. I am looking for a parser for .knxproj file (I implemented one but I am not 100% satisfied). I already use XKNX for sending/receiving telegram and thus I just found out about this project.

I would need to get the list of available group addresses for each device, already linked to a GA or not with available info (DPT, read/write, ...).

Is it something you plan to implement?

Thanks :)

**Comment by marvin-w** [comment]
Something that is currently missing is correctly parsing the COs. (see https://github.com/XKNX/xknxproject/issues/14 - although there is not a lot of text xD)

So yes, getting each device with all related GAs works, just not with read/write (or like, any) flags currently - thats #14.

Out of curiosity: What kind of open source research project about smart home and verification are you working on?

**Comment by samuelchassot** [comment]
Hi, thanks for your reply!

@farmio 
I saw this example and it does not contain every information I need: here only the comm objects that are assigned to a group address are shown. What I would need is a way to get all comm objects from projects with no group addresses defined yet (e.g., let's say you have a push button with 8 comm objects with DPT1-XXX, I need to get a list of these without having linked them to any GA).

**Comment by marvin-w** [comment]
> I saw this example and it does not contain every information I need: here only the comm objects that are assigned to a group address are shown. What I would need is a way to get all comm objects from projects with no group addresses defined yet (e.g., let's say you have a push button with 8 comm objects with DPT1-XXX, I need to get a list of these without having linked them to any GA).

We currently filter out empty com object references (that do not have a link assigned). See https://github.com/XKNX/xknxproject/blob/main/xknxproject/xml/parser.py#L56 and https://github.com/XKNX/xknxproject/blob/main/xknxproject/loader/topology_loader.py#L132.

You would need to change this in order to load all com objects. This is due to the fact that the purpose of this lib is to show users their project in a Web UI so they can easier configure their devices within Home Assistant. That's not yet implemented though.

**Comment by marvin-w** [comment]
> To give more context to my question about the parser, I would like to map an ETS project file to a list of available "abstract devices" supported by our tool. We also provide a KNX simulator. The end goal would be to provide a config for the simulator from the ETS project file alone. That's why I need to read all comm objects to map them to simulated device(s).

This is what we have been trying to do for the last two years :-), but we want to map it to Home Assistant entities/devices. Most entities (speaking for HA now) can not just be mapped to a single device within KNX.

Feel free to join our discord so we can discuss further.

**Comment by samuelchassot** [comment]
> > To give more context to my question about the parser, I would like to map an ETS project file to a list of available "abstract devices" supported by our tool. We also provide a KNX simulator. The end goal would be to provide a config for the simulator from the ETS project file alone. That's why I need to read all comm objects to map them to simulated device(s).
> 
> This is what we have been trying to do for the last two years :-), but we want to map it to Home Assistant entities/devices. Most entities (speaking for HA now) can not just be mapped to a single device within KNX.
> 
> Feel free to join our discord so we can discuss further.

I see! We tried to have our abstract devices as small and abstract as possible, so that a KNX device can be abstracted by a set of our devices :-)
I just joined the discord :)

**Comment by marvin-w** [comment]
> Cool! I'll try to modify it locally and maybe I'll open a PR to share if I achieve something :)

Sure :). I guess we can still filter out empty ones in the frontend, although the JSON gets a lot bigger. Maybe add a parameter to it if you intend to open a PR.

**Comment by samuelchassot** [comment]
> > Cool! I'll try to modify it locally and maybe I'll open a PR to share if I achieve something :)
> 
> Sure :). I guess we can still filter out empty ones in the frontend, although the JSON gets a lot bigger. Maybe add a parameter to it if you intend to open a PR.

Yep, makes sense to have a parameter rather than doing it by default. In my scala parser, I managed to read flags, I'll see if I can transpose :)
