### ISSUE TITLE
ETS Project navigation is missing

### ISSUE THREAD

**Issue by tmatrifork** [XKNX/xknxproject#348]
Hi!

I have added the KNX integration with success and everything seems ok.
I can see the "Info" and "Group Monitor" however I'm missing the "ETS Project" navigation. 

When adding my project the log says:
2024-01-09 12:52:57.305 INFO (SyncWorker_5) [xknxproject.log] Found 722 group addresses, 359 devices and 1354 used communication objects 

Please advice.

XKNX Version 2.11.2
KNX-Frontend Version 2023.6.23.191712
Connected to bus Yes
Individual address 13.0.255

Home Assistant: Core 2024.1.2
Supervisor 2023.12.0
Frontend 20240104.0

**Comment by farmio** [comment]
Hi 👋! 
It is not released yet.
https://github.com/XKNX/knx-frontend/issues/119
