### ISSUE TITLE
Failed to fetch Error on Project Upload

### ISSUE THREAD

**Issue by vohkts** [XKNX/xknxproject#393]
Hello,

when I try to upload my project file it idles for 3-4 Minutes end ends with an popup error "Failed to Fetch". Any hint? I got no relatable error in the logs.

**Comment by farmio** [comment]
Hi 👋! 
Never seen this error. Maybe check your browser logs if there is any hint.

**Comment by vohkts** [comment]
I already switched browser - "Failed to Fetch" on Chromium (Edge/Chrome) and "NetworkError when attempting to fetch resource" on firefox but both via Lovelace UI Popup. 
Im using the VMware Workstation Image of Home Assistant, cant seem to find anyone else that had equal issues in the past...

**Comment by vohkts** [comment]
Seems to be an general issue with the HAOS installation. A fresh installation with same configs fixes the issue.
