### ISSUE TITLE
Unable to upload/parse ETS project file

### ISSUE THREAD

**Issue by WebFactoryLtd** [XKNX/xknxproject#444]
Hi,
I'm having problems uploading/parsing my ETS project file. Fresh installation on HAOS 13 and HA core 2024.8.1.

All my projects are ETS6. I've tried several, from tiny to big - results are the same. Click browse, find file, hit submit - blue line starts going left/right, and everything stays like that for +30min. No error, no response, no nothing. Chrome console shows that http://homeassistant.local:8123/api/file_upload was called, but after that nothing. Didn't find anything in log either.

I tried downgrading HAOS to 12.4 - no change. Rebooted several times, emptied cache, tried another browsers - all the usual stuff, and still nothing.

Any guidance is highly appreciated. Thank you!

**Comment by marvin-w** [comment]
Hey, did the request finish or does it stay pending?

I'm not using HAOS myself, but I uploaded my ETS6 successfully yesterday with HA Container - so probably it's related to the setup variant somehow.

**Comment by farmio** [comment]
Hi 👋! 
Are you able to upload other files via HAs file_upload api? Eg. media files. 
Context: https://community.home-assistant.io/t/unable-to-upload-knx-ets-file-or-any-media-file/760326/1

**Comment by WebFactoryLtd** [comment]
@farmio no :( Same issue. I select a small MP4 and uploader just spins ... So it's not an ETS issue. It's a file upload issue. Do you have any idea where to start digging? I never got any file privilege errors. HA seems to work fine. I can install add-ons. And edit config via file editor. Running VMware on Win10 .

@marvin-w I now left it for about an hour and finally got a response! Msg box says "Upload failed Failed to fetch"

![image](https://github.com/user-attachments/assets/1b8580aa-d9d0-41c6-af32-f92cc23092eb)

**Comment by farmio** [comment]
Unfortunately I can't seem to reproduce this problem... and also don't know where to start looking. 

Unless Marvin has an idea, I'd suggest to open an issue at https://github.com/home-assistant/core tagging the "file_upload" integration to see if there is anyone more knowledgeable.

**Comment by marvin-w** [comment]
Can you do another upload and before uploading open the DevTools and open the Network Tab and check what you get as a response or if it is stuck pending for an hour?

**Comment by WebFactoryLtd** [comment]
@farmio will do, thank you!

@marvin-w took 21min this time, here's what I got. And I got the same "failed to fetch" response

![image](https://github.com/user-attachments/assets/bb052379-cb71-426f-9c17-efd092fd2b5b)
![image](https://github.com/user-attachments/assets/194a8080-8688-44cb-806f-81ad9e9b1bbd)

**Comment by farmio** [comment]
🤔 the other report (linked above) also runs Win10/VMWare. Is there something special about this? Would you have a different host to test (Raspberry or something)?

It works fine on a fresh macOS/UTM arm image.

**Comment by sotatech** [comment]
My HA test system runs 2024.8.2 under Hyper-V. I just tried uploading my project file from ETS 6.2.2 and it loaded fine.

**Comment by WebFactoryLtd** [comment]
Still on Windows, but switched to VirtualBox and everything works fine. So it's a VMware bug :(
