### ISSUE TITLE
KeyError in application_program_loader.py:88

### ISSUE THREAD

**Issue by envy** [XKNX/xknxproject#67]
Hi,

I watend to play around with xknxproject a bit and tried to load a project.

I got this error:

```
Traceback (most recent call last):
  File "/home/weichbr/xknxproject/test.py", line 6, in <module>
    project: KNXProject = knxproj.parse()
  File "/home/weichbr/xknxproject/xknxproject/knxproj.py", line 32, in parse
    return XMLParser(knx_project_content).parse()
  File "/home/weichbr/xknxproject/xknxproject/xml/parser.py", line 40, in parse
    self.load()
  File "/home/weichbr/xknxproject/xknxproject/xml/parser.py", line 155, in load
    ApplicationProgramLoader.load(application_program_file, devices)
  File "/home/weichbr/xknxproject/xknxproject/loader/application_program_loader.py", line 88, in load
    _com_object_ref = com_object_refs[com_instance.ref_id]
KeyError: 'M-0083_A-0098-11-29A3_MD-1_M-2_MI-1_O-2-0_R-99'
```

Sadly, I cannot share the knxproj file as it contains a lot of personal information. The project is simple, IP Backbone, one TP line.

To assist a bit with debugging, this is what I could figure out:
`com_object_refs` only contains 3 items:
```
ComObjectRef(identifier='M-0083_A-0098-11-29A3_O-72_R-10', ref_id='M-0083_A-0098-11-29A3_O-72', name=None, text=None, function_text=None, object_size=None, read_flag=None, write_flag=None, communication_flag=None, transmit_flag=None, update_flag=None, read_on_init_flag=None, datapoint_type=None)
ComObjectRef(identifier='M-0083_A-0098-11-29A3_O-79_R-4', ref_id='M-0083_A-0098-11-29A3_O-79', name=None, text=None, function_text=None, object_size=None, read_flag=None, write_flag=None, communication_flag=None, transmit_flag=None, update_flag=None, read_on_init_flag=None, datapoint_type=None)
ComObjectRef(identifier='M-0083_A-0098-11-29A3_O-80_R-146', ref_id='M-0083_A-0098-11-29A3_O-80', name=None, text='Temperature', function_text='Send measured value', object_size='2 Bytes', read_flag=True, write_flag=False, communication_flag=None, transmit_flag=None, update_flag=False, read_on_init_flag=None, datapoint_type={'main': 9, 'sub': 1})
```

`com_object_instance_refs` contains 47 objects

The offending `com_instance` is number 3 in that list:
```
ComObjectInstanceRef(identifier=None, ref_id='M-0083_A-0098-11-29A3_MD-1_M-2_MI-1_O-2-0_R-99', text='T3/4: Rollladen', function_text=None, read_flag=None, write_flag=None, communication_flag=None, transmit_flag=None, update_flag=None, read_on_init_flag=None, datapoint_type=None, description=None, links=['GA-23'], name=None, number=None, object_size=None)
```

`used_com_object_refs` contains 17 strings and `M-0083_A-0098-11-29A3_MD-1_M-2_MI-1_O-2-0_R-99` __is__ one of them.

I printed all the identifiers it loops over and all are missing the `MD-?_M-?_MI-?_` part:
![grafik](https://user-images.githubusercontent.com/241552/185225577-497af5e7-6501-465a-80fd-ad5d7f61826d.png)

Yet, there are a lot of comobjrefs that have these (`used_com_object_refs`):
![grafik](https://user-images.githubusercontent.com/241552/185225747-33c282a1-8145-43a0-a3bf-8f78a488024f.png)

Please let me know what I should investigate if you need more information.

**Comment by farmio** [comment]
Hm... M_ stands for Module / ModuleInstance / ModuleDef, but I have no idea what that is and how it works. 
What device is that? Anything special about that thing?
Can you send me the application file (unzip your project file and search for `M-0083/M-0083_A-0098-11-29A3`) per Discord?

**Comment by envy** [comment]
It's a MDT Taster Smart 55 with temperature.

Will send the file.

**Comment by marvin-w** [comment]
M is the manufacturer imho

**Comment by farmio** [comment]
I wonder what Submodules are then. We should find a device using that 🤔
![image](https://user-images.githubusercontent.com/12422879/185304014-4be23a8a-8704-4c13-83e8-496abbc4dd30.jpeg)

**Comment by farmio** [comment]
I think it would work this way:
- In the project file (0.xml) we have to search for
```xml
<ModuleInstances>
                  <ModuleInstance Id="MD-1_M-2_MI-1" RefId="MD-1_M-2" RepeatIndex="502x1">
```
- match `ComObjectInstanceRef[RefId]` with `startswith()` to the found IDs to get the RefId of a used Module
- In the application file search for `Module` with found Ids
```xml
<Module Id="M-0083_A-0098-11-29A3_MD-1_M-2" RefId="M-0083_A-0098-11-29A3_MD-1">
```
- use the RefId of a Module to prepend the `ComObjectInstanceRef[RefId]` (stripped by all `M?-*` occurrences - this is where it gets ugly imho) with to resolve the correct ComObjectInstanceRef Tag (instead of `hardware.application_program_ref`)

Would probably help if we parsed the `ComObjectInstanceRef[RefId]` to a dict or tuple to have separated identifiers (`O-`, `R-`, `M-`, etc.) but I'm not sure if order is guaranteed. I made a ticket at KNXA to ask that - lets see if I get a reply.
